-- ============================================================
-- NeuralChat — Supabase Schema
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================

-- 1. Follow-up queue (scheduled by browser, processed by cron)
create table if not exists followup_queue (
  id            uuid        default gen_random_uuid() primary key,
  user_id       text        not null,
  char_id       text        not null,
  char_config   jsonb       not null,          -- { name, avatar, avatarImg, model }
  context_msg   text        not null,          -- last AI message (context for generation)
  system_prompt text        not null default '',
  scheduled_at  timestamptz not null,          -- when to fire
  followup_index int        not null default 0,
  relationship  text        not null default 'casual',   -- pacar / sahabat / casual
  personality   text        not null default 'caring',   -- curious / caring / clingy / chill
  api_key       text        not null,          -- user's OpenRouter key
  openrouter_model text     not null default 'google/gemini-2.0-flash-001',
  fired         boolean     not null default false,
  fired_by      text        default null,      -- 'browser' | 'cron' | 'cancelled'
  result_msg    text        default null,      -- generated follow-up text
  fired_at      timestamptz default null,
  created_at    timestamptz default now()
);

create index if not exists idx_followup_queue_due
  on followup_queue (fired, scheduled_at)
  where fired = false;

create index if not exists idx_followup_queue_user_char
  on followup_queue (user_id, char_id);

-- 2. Delivered follow-ups (messages generated by cron, waiting for browser pick-up)
create table if not exists delivered_followups (
  id        uuid        default gen_random_uuid() primary key,
  user_id   text        not null,
  char_id   text        not null,
  messages  jsonb       not null,    -- array of { id, role, content, timestamp, isFollowUp, fromCron }
  delivered boolean     not null default false,
  created_at timestamptz default now()
);

create index if not exists idx_delivered_followups_pending
  on delivered_followups (user_id, char_id, delivered)
  where delivered = false;

-- 3. Push notification subscriptions
create table if not exists push_subscriptions (
  id           uuid        default gen_random_uuid() primary key,
  user_id      text        not null unique,
  subscription jsonb       not null,    -- Web Push subscription object
  updated_at   timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- All access goes through service role key (server-side only)
-- Disable RLS or use service role — do NOT expose anon key
-- ============================================================
alter table followup_queue      disable row level security;
alter table delivered_followups disable row level security;
alter table push_subscriptions  disable row level security;

-- ============================================================
-- Cleanup old fired follow-ups (optional scheduled job)
-- Run manually or via pg_cron to keep table clean:
-- DELETE FROM followup_queue WHERE fired = true AND created_at < now() - interval '7 days';
-- DELETE FROM delivered_followups WHERE delivered = true AND created_at < now() - interval '3 days';
-- ============================================================
