// api/followups/delivered.js
// Browser polls this when user opens/switches to a character
// Returns messages generated by cron while browser was closed, then marks them delivered

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

export default async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { userId, charId } = req.query;

  if (!userId || !charId) {
    return res.status(400).json({ error: 'Missing userId or charId' });
  }

  // Fetch all undelivered messages for this user+char
  const { data, error } = await supabase
    .from('delivered_followups')
    .select('id, messages, created_at')
    .eq('user_id', userId)
    .eq('char_id', charId)
    .eq('delivered', false)
    .order('created_at', { ascending: true });

  if (error) {
    console.error('[delivered] Supabase error:', error);
    return res.status(500).json({ error: error.message });
  }

  if (!data?.length) {
    return res.status(200).json({ messages: [] });
  }

  // Mark as delivered so we don't return them again
  const ids = data.map(d => d.id);
  await supabase
    .from('delivered_followups')
    .update({ delivered: true })
    .in('id', ids);

  // Flatten all messages from all batches, sorted by timestamp
  const messages = data
    .flatMap(d => d.messages || [])
    .sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0));

  return res.status(200).json({ messages, batches: data.length });
}
